//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControleEmprestimo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprestimos
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataEmprestimo { get; set; }
        public int IdAmigo { get; set; }
        public int IdJogo { get; set; }
    
        public virtual Amigos Amigos { get; set; }
        public virtual Jogos Jogos { get; set; }
    }
}
